# Generated by Django 4.2 on 2023-05-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='category',
            field=models.CharField(choices=[('question', 'pytanie'), ('other', 'inne')], max_length=100),
        ),
    ]
